apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ci-helper-app
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/psturc-tenant/ci-helper-app/ci-helper-app@sha256:add6f5a82ff310b84878fd525b305503c43869b6dbc4e3a76c0a6df46f7bce1e
        name: ci-helper-app
        resources: {}
status: {}
